Repository palantir/osdk-ts, pull requests merged in 2024-04, with the labels that each got.

#160 Rename to _gitignore inside templates
  packages/create-app/changelog/@unreleased/pr-160.v2.yml
  packages/create-app/src/run.ts
  packages/create-app/templates/template-next-static-export/_gitignore
  packages/create-app/templates/template-react/_gitignore
  packages/create-app/templates/template-vue/_gitignore
Labels: merge when ready

#167 Delete packages/cli/sample directory
  packages/cli/sample/index.html
Labels: merge when ready, no changelog

#171 Bump vitest
  package.json
  packages/generator-converters/package.json
  packages/generator/package.json
  packages/maker/package.json
  pnpm-lock.yaml
Labels: merge when ready, no changelog

#170 Fix query params based omni api calls
  packages/omniapi-generator/src/generateResource.ts
  packages/omniapi/src/public/Datasets_Branch.ts
  packages/omniapi/src/public/Datasets_Dataset.ts
  packages/omniapi/src/public/Datasets_File.ts
  packages/omniapi/src/public/Datasets_Transaction.ts
  packages/omniapi/src/public/Models_LanguageModel.ts
  packages/omniapi/src/public/OntologiesV2_Action.ts
  packages/omniapi/src/public/OntologiesV2_ActionTypeV2.ts
  packages/omniapi/src/public/OntologiesV2_ObjectTypeV2.ts
  packages/omniapi/src/public/OntologiesV2_OntologyObjectSet.ts
  packages/omniapi/src/public/OntologiesV2_OntologyObjectV2.ts
  packages/omniapi/src/public/OntologiesV2_QueryType.ts
Labels: merge when ready, no changelog

#179 Update generateResource.ts
  packages/omniapi-generator/src/generateResource.ts
Labels: merge when ready, no changelog

#166 Switch site commands to public API
  packages/cli.common/changelog/@unreleased/pr-166.v2.yml
  packages/cli.common/src/ExitProcessError.ts
  packages/cli/changelog/@unreleased/pr-166.v2.yml
  packages/cli/src/commands/site/deploy/siteDeployCommand.mts
  packages/cli/src/commands/site/version/delete/versionDeleteCommand.mts
  packages/cli/src/commands/site/version/get/versionGetCommand.mts
  packages/cli/src/commands/site/version/list/versionListCommand.mts
  packages/cli/src/commands/site/version/set/versionSetCommand.mts
  packages/cli/src/commands/site/version/unset/versionUnsetCommand.mts
  packages/cli/src/generated/artifacts-sites/ArtifactsSitesAdminV2Service.ts
  packages/cli/src/generated/artifacts-sites/ArtifactsSitesAdminV2Service/clearDeployedVersion.ts
  packages/cli/src/generated/artifacts-sites/ArtifactsSitesAdminV2Service/getDeployedVersion.ts
  packages/cli/src/generated/artifacts-sites/ArtifactsSitesAdminV2Service/getRegisteredSiteDomains.ts
  packages/cli/src/generated/artifacts-sites/ArtifactsSitesAdminV2Service/getRequestedSiteDomains.ts
  packages/cli/src/generated/artifacts-sites/ArtifactsSitesAdminV2Service/previewContentSecurityPolicy.ts
  packages/cli/src/generated/artifacts-sites/ArtifactsSitesAdminV2Service/putContentSecurityPolicyAdditions.ts
  packages/cli/src/generated/artifacts-sites/ArtifactsSitesAdminV2Service/requestSiteDomainForRepository.ts
  packages/cli/src/generated/artifacts-sites/ArtifactsSitesAdminV2Service/unregisterSiteDomain.ts
  packages/cli/src/generated/artifacts-sites/ContentSecurityPolicyAdditions.ts
  packages/cli/src/generated/artifacts-sites/ContentSecurityPolicyDirectiveName.ts
  packages/cli/src/generated/artifacts-sites/ContentSecurityPolicyDirectiveValue.ts
  packages/cli/src/generated/artifacts-sites/ContentSecurityPolicyHeaderValue.ts
  packages/cli/src/generated/artifacts-sites/ControlPanelManagedDomainInfo.ts
  packages/cli/src/generated/artifacts-sites/DomainName.ts
  packages/cli/src/generated/artifacts-sites/PreviewContentSecurityPolicyRequest.ts
  packages/cli/src/generated/artifacts-sites/SiteDomainInfo.ts
  packages/cli/src/generated/artifacts-sites/SiteVersion.ts
  packages/cli/src/generated/artifacts-sites/SubmitDomainRegistrationRequest.ts
  packages/cli/src/generated/artifacts-sites/UpdateDeployedVersionRequest.ts
  packages/cli/src/generated/artifacts-sites/index.ts
  packages/cli/src/net/RepositoryRid.ts
  packages/cli/src/net/artifacts/SiteAssetArtifactsService/DeleteSiteVersionRequest.mts
  packages/cli/src/net/artifacts/SiteAssetArtifactsService/SiteAssetVersions.mts
  packages/cli/src/net/artifacts/SiteAssetArtifactsService/UploadZippedSiteAssetRequest.mts
  packages/cli/src/net/artifacts/SiteAssetArtifactsService/deleteSiteVersion.mts
  packages/cli/src/net/artifacts/SiteAssetArtifactsService/fetchSiteVersions.mts
  packages/cli/src/net/artifacts/SiteAssetArtifactsService/getSiteAssetBaseUrl.mts
  packages/cli/src/net/artifacts/SiteAssetArtifactsService/index.mts
  packages/cli/src/net/artifacts/SiteAssetArtifactsService/uploadSiteVersion.mts
  packages/cli/src/net/artifacts/index.mts
  packages/cli/src/net/createConjureContext.mts
  packages/cli/src/net/createFetch.mts
  packages/cli/src/net/index.mts
  packages/cli/src/net/third-party-application-service/index.mts
  packages/cli/src/net/third-party-applications/ListWebsiteVersionsResponse.mts
  packages/cli/src/net/third-party-applications/UpdateWebsiteDeploymentRequest.mts
  packages/cli/src/net/third-party-applications/WebsiteDeployment.mts
  packages/cli/src/net/third-party-applications/WebsiteVersion.mts
  packages/cli/src/net/third-party-applications/deleteWebsiteDeployment.mts
  packages/cli/src/net/third-party-applications/deleteWebsiteVersion.mts
  packages/cli/src/net/third-party-applications/getWebsiteDeployment.mts
  packages/cli/src/net/third-party-applications/index.mts
  packages/cli/src/net/third-party-applications/listWebsiteVersions.mts
  packages/cli/src/net/third-party-applications/updateWebsiteDeployment.mts
  packages/cli/src/net/third-party-applications/uploadWebsiteVersion.mts
Labels: merge when ready

#186 Fix formatting
  packages/cli/package.json
Labels: merge when ready, no changelog

#181 Dont dump file contents on build output
  packages/generator/src/v1.1/generateClientSdkVersionOneDotOne.test.ts
Labels: no changelog

#208 Bump major version
  .github/workflows/release.yml
  packages/foundry-sdk-generator/CHANGELOG.md
  packages/foundry-sdk-generator/package.json
Labels: no changelog

#223 use ranges in our published deps
  examples-extra/basic/cli/package.json
  examples-extra/basic/sdk/package.json
  examples-extra/docs_example/package.json
  examples-extra/one_dot_one/package.json
  examples-extra/todoapp/package.json
  package.json
  packages/api/package.json
  packages/cli.cmd.typescript/package.json
  packages/cli/package.json
  packages/client/package.json
  packages/example-generator/package.json
  packages/foundry-sdk-generator/package.json
  packages/generator-converters/package.json
  packages/generator/package.json
  packages/legacy-client/package.json
  packages/maker/package.json
  packages/omniapi/package.json
  packages/shared.net/package.json
  packages/shared.test/package.json
  pnpm-lock.yaml
  tests/verify-fallback-package-v2/package.json
  tests/verify-fallback-package/package.json
Labels: merge when ready

#220 Improvements to changesets
  .changeset/eleven-dolphins-confess.md
  package.json
  packages/tool.release/package.json
  packages/tool.release/src/FailedWithUserMessage.ts
  packages/tool.release/src/index.ts
  packages/tool.release/src/mutateReleasePlan.test.ts
  packages/tool.release/src/mutateReleasePlan.ts
  packages/tool.release/src/runVersion.ts
  pnpm-lock.yaml
  scripts/createReleasePr.sh
Labels: merge when ready

#226 Make snapshots always follow releases
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: merge when ready

#234 upgrade msw
  .changeset/twenty-eggs-laugh.md
  packages/client/src/ontology/StandardOntologyProvider.test.ts
  packages/shared.test/package.json
  packages/shared.test/src/handlers/actionEndpoints.ts
  packages/shared.test/src/handlers/commonHandlers.ts
  packages/shared.test/src/handlers/loadObjectsEndpoints.ts
  packages/shared.test/src/handlers/multipassServer.ts
  packages/shared.test/src/handlers/objectSetEndpoints.ts
  packages/shared.test/src/handlers/ontologyMetadataEndpoints.ts
  packages/shared.test/src/handlers/unsupportedMetadataHandler.ts
  packages/shared.test/src/handlers/util/handleOpenApiCall.ts
  pnpm-lock.yaml
Labels: merge when ready

#249 Update site APIs
  .changeset/soft-ears-vanish.md
  packages/cli/src/commands/site/deploy/siteDeployCommand.mts
  packages/cli/src/commands/site/version/delete/versionDeleteCommand.mts
  packages/cli/src/commands/site/version/get/versionGetCommand.mts
  packages/cli/src/commands/site/version/list/versionListCommand.mts
  packages/cli/src/commands/site/version/set/versionSetCommand.mts
  packages/cli/src/commands/site/version/unset/versionUnsetCommand.mts
  packages/cli/src/net/createFetch.mts
  packages/cli/src/net/third-party-applications/DeployWebsiteRequest.mts
  packages/cli/src/net/third-party-applications/ListVersionsResponse.mts
  packages/cli/src/net/third-party-applications/Version.mts
  packages/cli/src/net/third-party-applications/Website.mts
  packages/cli/src/net/third-party-applications/deleteVersion.mts
  packages/cli/src/net/third-party-applications/deployWebsite.mts
  packages/cli/src/net/third-party-applications/getWebsite.mts
  packages/cli/src/net/third-party-applications/index.mts
  packages/cli/src/net/third-party-applications/listVersions.mts
  packages/cli/src/net/third-party-applications/undeployWebsite.mts
  packages/cli/src/net/third-party-applications/uploadVersion.mts
Labels: merge when ready

#187 Move site command out of unstable
  .changeset/great-wolves-grow.md
  packages/cli/src/cli.ts
Labels: merge when ready

#92 Improvement: Add @osdk/cli README
  packages/cli/README.md
Labels: merge when ready
