Repository palantir/osdk-ts, pull requests merged in 2024-02, with the labels that each got.

#25 Upgrade some dependencies
  examples/todoapp/package.json
  package.json
  packages/generator/package.json
  pnpm-lock.yaml
Labels: no changelog

#26 Enable yargs cli version for @osdk/create-app
  packages/create-app/changelog/@unreleased/pr-26.v2.yml
  packages/create-app/src/cli.ts
Labels: merge when ready

#27 Remove getMethods in templates
  packages/create-app/.gitignore
  packages/create-app/changelog/@unreleased/pr-27.v2.yml
  packages/create-app/src/__tests__/__snapshots__/expected-template-next-static-export/src/app/page.tsx
  packages/create-app/src/__tests__/__snapshots__/expected-template-next-static-export/src/lib/client.ts
  packages/create-app/src/__tests__/__snapshots__/expected-template-next-static-export/src/lib/useAuthenticated.ts
  packages/create-app/src/__tests__/__snapshots__/expected-template-react/src/Home.tsx
  packages/create-app/src/__tests__/__snapshots__/expected-template-react/src/getMethods.ts
  packages/create-app/src/__tests__/__snapshots__/expected-template-vue/src/Home.vue
  packages/create-app/src/__tests__/__snapshots__/expected-template-vue/src/getMethods.ts
  packages/create-app/templates/template-next-static-export/src/app/page.tsx.hbs
  packages/create-app/templates/template-next-static-export/src/lib/client.ts.hbs
  packages/create-app/templates/template-next-static-export/src/lib/useAuthenticated.ts
  packages/create-app/templates/template-react/src/Home.tsx.hbs
  packages/create-app/templates/template-react/src/getMethods.ts
  packages/create-app/templates/template-vue/src/Home.vue.hbs
  packages/create-app/templates/template-vue/src/getMethods.ts
Labels: merge when ready

#35 Fix: git describe using regex instead of glob for autoVersion util
  packages/cli/changelog/@unreleased/pr-35.v2.yml
  packages/cli/src/util/autoVersion.test.ts
  packages/cli/src/util/autoVersion.ts
Labels: merge when ready

#22 Update docs about changelog/release process
  .changeset/README.md
  .monorepolint.config.mjs
  README.md
  examples/basic/cli/package.json
  examples/basic/sdk/package.json
  examples/one_dot_one/CHANGELOG_OLD.md
  examples/one_dot_one/package.json
  examples/todoapp/CHANGELOG_OLD.md
  packages/api/CHANGELOG_OLD.md
  packages/api/package.json
  packages/cli/CHANGELOG_OLD.md
  packages/cli/package.json
  packages/client/CHANGELOG_OLD.md
  packages/client/package.json
  packages/foundry-sdk-generator/CHANGELOG_OLD.md
  packages/foundry-sdk-generator/package.json
  packages/gateway-generator/CHANGELOG_OLD.md
  packages/gateway-generator/package.json
  packages/gateway/CHANGELOG_OLD.md
  packages/gateway/package.json
  packages/generator/CHANGELOG_OLD.md
  packages/generator/package.json
  packages/legacy-client/CHANGELOG_OLD.md
  packages/legacy-client/package.json
  packages/shared.net/CHANGELOG_OLD.md
  packages/shared.net/package.json
  packages/shared.test/CHANGELOG_OLD.md
  packages/shared.test/package.json
  tests/verify-fallback-package/CHANGELOG_OLD.md
Labels: no changelog

#37 Fix monorepolint semantic merge conflict
  packages/create-app/package.json
Labels: merge when ready, no changelog

#32 Refactor create-app prompts with tests
  packages/create-app/changelog/@unreleased/pr-32.v2.yml
  packages/create-app/src/cli.ts
  packages/create-app/src/prompts/promptApplicationUrl.test.ts
  packages/create-app/src/prompts/promptApplicationUrl.ts
  packages/create-app/src/prompts/promptClientId.test.ts
  packages/create-app/src/prompts/promptClientId.ts
  packages/create-app/src/prompts/promptFoundryUrl.test.ts
  packages/create-app/src/prompts/promptFoundryUrl.ts
  packages/create-app/src/prompts/promptOsdkPackage.test.ts
  packages/create-app/src/prompts/promptOsdkPackage.ts
  packages/create-app/src/prompts/promptOsdkRegistryUrl.test.ts
  packages/create-app/src/prompts/promptOsdkRegistryUrl.ts
  packages/create-app/src/prompts/promptOverwrite.test.ts
  packages/create-app/src/prompts/promptOverwrite.ts
  packages/create-app/src/prompts/promptProject.test.ts
  packages/create-app/src/prompts/promptProject.ts
  packages/create-app/src/prompts/promptTemplate.test.ts
  packages/create-app/src/prompts/promptTemplate.ts
Labels: merge when ready

#40 Update create-app to use FOUNDRY_TOKEN in templates
  packages/create-app/changelog/@unreleased/pr-40.v2.yml
  packages/create-app/src/__snapshots__/expected-template-next-static-export/.npmrc
  packages/create-app/src/__snapshots__/expected-template-react/.npmrc
  packages/create-app/src/__snapshots__/expected-template-vue/.npmrc
  packages/create-app/src/cli.ts
  packages/create-app/src/generate/generateNpmRc.test.ts
  packages/create-app/src/generate/generateNpmRc.ts
Labels: merge when ready

#42 Move argv override logging to middleware
  packages/cli/changelog/@unreleased/pr-42.v2.yml
  packages/cli/src/commands/site/deploy/index.ts
  packages/cli/src/commands/site/deploy/logDeployCommandConfigFileOverride.ts
  packages/cli/src/commands/site/index.ts
  packages/cli/src/commands/site/logSiteCommandConfigFileOverride.ts
  packages/cli/src/util/config.ts
Labels: merge when ready

#41 Display errors more consistently in @osdk/cli
  packages/cli/changelog/@unreleased/pr-41.v2.yml
  packages/cli/src/YargsCheckError.ts
  packages/cli/src/cli.ts
  packages/cli/src/commands/site/deploy/index.ts
  packages/cli/src/commands/site/deploy/siteDeployCommand.mts
  packages/cli/src/commands/site/index.ts
  packages/cli/src/net/artifacts/SiteAssetArtifactsService/fetchSiteVersions.mts
  packages/cli/src/net/third-party-application-service/fetchWebsiteRepositoryRid.mts
  packages/cli/src/util/autoVersion.ts
  packages/cli/src/util/config.test.ts
  packages/cli/src/util/config.ts
  packages/cli/src/util/token.ts
  packages/cli/src/yargs/logVersionMiddleware.ts
Labels: merge when ready

#51 Clean up yargs and consola imports
  packages/cli/changelog/@unreleased/pr-51.v2.yml
  packages/cli/src/cli.ts
  packages/cli/src/commands/site/deploy/index.ts
  packages/cli/src/commands/site/deploy/logDeployCommandConfigFileOverride.ts
  packages/cli/src/commands/site/index.ts
  packages/cli/src/commands/site/logSiteCommandConfigFileOverride.ts
  packages/cli/src/commands/typescript/generate/generate.ts
  packages/cli/src/util/config.ts
  packages/cli/src/yargs/logConfigFileMiddleware.ts
  packages/cli/src/yargs/logVersionMiddleware.ts
Labels: merge when ready

#49 Debug log site zip stats
  packages/cli/changelog/@unreleased/pr-49.v2.yml
  packages/cli/src/commands/site/deploy/siteDeployCommand.mts
Labels: merge when ready

#47 Increase CLI max width to 150 columns
  packages/cli/changelog/@unreleased/pr-47.v2.yml
  packages/cli/src/cli.ts
Labels: merge when ready

#54 Review CLI wording
  packages/cli/changelog/@unreleased/pr-54.v2.yml
  packages/cli/src/commands/site/deploy/index.ts
  packages/cli/src/commands/site/index.ts
  packages/cli/src/commands/site/version/delete/index.ts
  packages/cli/src/commands/site/version/get/index.ts
  packages/cli/src/commands/site/version/index.ts
  packages/cli/src/commands/site/version/list/index.ts
  packages/cli/src/commands/site/version/set/index.ts
  packages/cli/src/commands/site/version/unset/index.ts
  packages/cli/src/commands/typescript/generate/generate.ts
Labels: merge when ready

#57 Display site link after deploy
  packages/cli/src/commands/site/deploy/siteDeployCommand.mts
  packages/cli/src/net/index.mts
Labels: merge when ready

#58 Refactor site link consola box code
  packages/cli/changelog/@unreleased/pr-58.v2.yml
  packages/cli/src/commands/site/deploy/siteDeployCommand.mts
Labels: merge when ready

#52 Handle version/autoVersion selection in the parsing layer
  packages/cli/changelog/@unreleased/pr-52.v2.yml
  packages/cli/src/commands/site/deploy/SiteDeployArgs.ts
  packages/cli/src/commands/site/deploy/index.ts
  packages/cli/src/commands/site/deploy/siteDeployCommand.mts
  packages/cli/src/util/config.ts
Labels: merge when ready

#60 Include repository link in package.json
  .monorepolint.config.mjs
  examples/basic/cli/package.json
  examples/basic/sdk/package.json
  examples/one_dot_one/package.json
  examples/todoapp/package.json
  monorepo/eslint-config-sane/package.json
  monorepo/mytsup/package.json
  monorepo/tsconfig/package.json
  packages/api/package.json
  packages/cli/package.json
  packages/client/package.json
  packages/create-app/package.json
  packages/foundry-sdk-generator/package.json
  packages/gateway-generator/package.json
  packages/gateway/package.json
  packages/generator/package.json
  packages/legacy-client/package.json
  packages/shared.net/package.json
  packages/shared.test/package.json
  tests/verify-fallback-package/package.json
Labels: merge when ready, no changelog

#50 Harmonize usage of options `foundryUrl` & `clientId` across all cli commands
  packages/cli/changelog/@unreleased/pr-50.v2.yml
  packages/cli/src/commands/auth/CommonAuthArgs.ts
  packages/cli/src/commands/auth/index.ts
  packages/cli/src/commands/auth/login/LoginArgs.ts
  packages/cli/src/commands/auth/login/index.ts
  packages/cli/src/commands/auth/login/loginFlow.ts
  packages/cli/src/commands/typescript/generate/TypescriptGenerateArgs.ts
  packages/cli/src/commands/typescript/generate/generate.ts
  packages/cli/src/commands/typescript/generate/handleGenerate.mts
Labels: merge when ready

#63 Update ExitProcessError tips and use option instead of argument
  packages/cli/changelog/@unreleased/pr-63.v2.yml
  packages/cli/src/util/autoVersion.test.ts
  packages/cli/src/util/autoVersion.ts
  packages/cli/src/util/token.ts
  packages/create-app/changelog/@unreleased/pr-63.v2.yml
  packages/create-app/src/cli.ts
Labels: merge when ready

#62 Enable eslint eqeqeq rule
  examples/basic/cli/src/index.ts
  monorepo/eslint-config-sane/library.cjs
  packages/client/src/internal/conversions/legacyToModernSingleAggregationResult.ts
  packages/generator/src/shared/wireObjectTypeV2ToSdkObjectConst.ts
  packages/generator/src/shared/wireQueryDataTypeToQueryDataTypeDefinition.ts
  packages/legacy-client/src/client/net/getOnlyLinkedObject.ts
  packages/legacy-client/src/client/objects/convertWireToOsdkObject.ts
  packages/shared.test/src/handlers/loadObjectsEndpoints.ts
Labels: merge when ready, no changelog

#68 Polish casing, option description, and YargsCheckErrors across CLIs and commands
  packages/cli/changelog/@unreleased/pr-68.v2.yml
  packages/cli/src/commands/auth/index.ts
  packages/cli/src/commands/auth/login/index.ts
  packages/cli/src/commands/site/deploy/index.ts
  packages/cli/src/commands/site/index.ts
  packages/cli/src/commands/typescript/generate/generate.ts
  packages/cli/src/commands/typescript/generate/handleGenerate.mts
  packages/create-app/changelog/@unreleased/pr-68.v2.yml
  packages/create-app/src/cli.ts
Labels: merge when ready

#71 Check client env variables at runtime
  packages/create-app/changelog/@unreleased/pr-71.v2.yml
  packages/create-app/src/__snapshots__/expected-template-next-static-export/src/lib/client.ts
  packages/create-app/src/__snapshots__/expected-template-react/src/client.ts
  packages/create-app/src/__snapshots__/expected-template-vue/src/client.ts
  packages/create-app/src/generate/generateEnv.test.ts
  packages/create-app/src/generate/generateEnv.ts
  packages/create-app/templates/template-next-static-export/src/lib/client.ts.hbs
  packages/create-app/templates/template-react/src/client.ts.hbs
  packages/create-app/templates/template-vue/src/client.ts.hbs
Labels: merge when ready

#76 Address feedback on create-app
  packages/create-app/README.md
  packages/create-app/changelog/@unreleased/pr-76.v2.yml
  packages/create-app/src/__snapshots__/expected-template-next-static-export/public/dev-console.svg
  packages/create-app/src/__snapshots__/expected-template-next-static-export/src/app/icon.svg
  packages/create-app/src/__snapshots__/expected-template-next-static-export/src/app/layout.tsx
  packages/create-app/src/__snapshots__/expected-template-next-static-export/src/app/page.tsx
  packages/create-app/src/__snapshots__/expected-template-react/index.html
  packages/create-app/src/__snapshots__/expected-template-react/public/dev-console.svg
  packages/create-app/src/__snapshots__/expected-template-react/src/Home.tsx
  packages/create-app/src/__snapshots__/expected-template-react/src/Layout.tsx
  packages/create-app/src/__snapshots__/expected-template-vue/index.html
  packages/create-app/src/__snapshots__/expected-template-vue/public/dev-console.svg
  packages/create-app/src/__snapshots__/expected-template-vue/src/Home.vue
  packages/create-app/src/__snapshots__/expected-template-vue/src/Layout.vue
  packages/create-app/src/__snapshots__/expected-template-vue/src/Login.vue
  packages/create-app/src/cli.ts
  packages/create-app/src/prompts/promptApplicationRid.ts
  packages/create-app/src/prompts/promptApplicationUrl.ts
  packages/create-app/src/prompts/promptClientId.ts
  packages/create-app/src/prompts/promptFoundryUrl.ts
  packages/create-app/src/prompts/promptOsdkPackage.ts
  packages/create-app/src/prompts/promptOsdkRegistryUrl.ts
  packages/create-app/templates/template-next-static-export/public/dev-console.svg
  packages/create-app/templates/template-next-static-export/src/app/icon.svg
  packages/create-app/templates/template-next-static-export/src/app/layout.tsx
  packages/create-app/templates/template-next-static-export/src/app/page.tsx.hbs
  packages/create-app/templates/template-react/index.html
  packages/create-app/templates/template-react/public/dev-console.svg
  packages/create-app/templates/template-react/src/Home.tsx.hbs
  packages/create-app/templates/template-react/src/Layout.tsx
  packages/create-app/templates/template-vue/index.html
  packages/create-app/templates/template-vue/public/dev-console.svg
  packages/create-app/templates/template-vue/src/Home.vue.hbs
  packages/create-app/templates/template-vue/src/Layout.vue
  packages/create-app/templates/template-vue/src/Login.vue
Labels: merge when ready

#77 Accept template id without prefix as template name
  packages/create-app/README.md
  packages/create-app/changelog/@unreleased/pr-77.v2.yml
  packages/create-app/src/prompts/promptTemplate.test.ts
  packages/create-app/src/prompts/promptTemplate.ts
Labels: merge when ready

#81 Update actions to pnpm/action-setup@v3, actions/setup-node@v4
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: merge when ready

#85 Actually provide a useful error when the cli can't generate stuff
  packages/generator/src/shared/wirePropertyV2ToSdkPropertyDefinition.ts
Labels: merge when ready

#87 Improve create-app snapshot failure messages
  packages/create-app/src/cli.test.ts
Labels: merge when ready, no changelog

#97 Improve no site versions found message
  packages/cli/changelog/@unreleased/pr-97.v2.yml
  packages/cli/src/commands/site/version/list/versionListCommand.mts
Labels: merge when ready
